version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projetoLaudosApp
    ports:
      - "80:80"
    networks:
      - laravel-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: projetoLaudosDb
    environment:
      
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: abc123
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: projetoLaudoInterfaceBanco
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: abc123
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge